### PR TITLE
Add some -Werror flags

### PR DESCRIPTION
**Pull request by andy-morris**
It turned out there are already are a couple of nonexhaustive matches so I think I should fix those before merging this

### CODE REVIEW

**Comment by andy-morris** [comment]
I did the ones I could but I don't know enough about Michelson or interaction nets to finish these definitions:

- `Juvix.Interpreter.InteractionNet.interactionNetASTToErasedCore`
- `Juvix.Backends.Michelson.DSL.Instructions.toNumArgs`
- `Juvix.Backends.Michelson.Parameterisation.{typeOf,constType}`

**Comment by andy-morris** [comment]
Changed back to a warning just for those modules for now.

**Comment by andy-morris** [comment]
@mariari @thealmarty would this change be too disruptive to your way of working? If so maybe this could be hidden behind a package flag which is enabled in the CI or something

**Comment by thealmarty** [comment]
> @mariari @thealmarty would this change be too disruptive to your way of working? If so maybe this could be hidden behind a package flag which is enabled in the CI or something

Not at all! I prefer turning on `-Werror` too! I have suggested this before. Thanks for this!

**Comment by mariari** [comment]
> @mariari @thealmarty would this change be too disruptive to your way of working? If so maybe this could be hidden behind a package flag which is enabled in the CI or something

The main issue I have with this, is that when I want to write new code (or refactor existing code), I often want to play with types in the repl or query it for information.

So being forced to first finish said changes (manually doing it in steps from the repl->File before playing around with forms), would likely disrupt how I flow.

With that said, I'd prefer it to happen on `stack build` that way we get the error behavior without it screwing with the haskell REPL.

If we can't do that, then the CI thing would be good

**Comment by andy-morris** [comment]
I thought that might be the case. I moved it into a package flag `incomplete-error`, which the CI uses, and you can use yourself with `stack build --flag juvix:incomplete-error`.

I also noticed that `package.yaml` contained `-j6`. I changed it to just `-j` to base the number of jobs on many cores the current machine has.

**Comment by andy-morris** [comment]
The arithmetic circuit stuff has some missing cases and methods. I demoted the errors to warnings in those modules too, but if it is easy to complete the code it would probably be better to do that if someone that understands that part of the code has the chance.

**Comment by andy-morris** [comment]
Oops! #417

**Comment by cwgoes** [comment]
Can we merge this or do you want to wait on https://github.com/metastatedev/juvix/pull/417?

**Comment by cwgoes** [comment]
(bump)

**Pull request merged**
