### PR TITLE
Release prep; testing

### PR DESCRIPTION
**Pull request by cwgoes**
Release prep.

### CODE REVIEW

**Comment by cwgoes** [comment]
Now with:

```bash
juvix parse test/examples/Id-Strings.ju
```

I get

```bash
juvix: Prelude.undefined
CallStack (from HasCallStack):
  error, called at src/Debug.hs:66:13 in protolude-0.2.4-Gn8RSsqHn6hJQNfqYGye6Z:Debug
```

Are there `undefined`s in the parser somewhere? cc @mariari

**Comment by mariari** [comment]
> Now with:
> 
> ```shell
> juvix parse test/examples/Id-Strings.ju
> ```
> 
> I get
> 
> ```shell
> juvix: Prelude.undefined
> CallStack (from HasCallStack):
>   error, called at src/Debug.hs:66:13 in protolude-0.2.4-Gn8RSsqHn6hJQNfqYGye6Z:Debug
> ```
> 
> Are there `undefined`s in the parser somewhere? cc @mariari

The error comes in the Prelude namely
```juvix
declare infixr (:) 2
```
since we have no way of declaring the definition.

we could remove this for now.

Also for the `Id-Strings` example we need to explicitly need to write `open Prelude` for now.

**Comment by cwgoes** [comment]
Thanks, made the suggested changes. Now I get:

```bash
ParseErr "endOfInput`
```

**Comment by cwgoes** [comment]
Now:

```bash
juvix parse test/examples/Id-Strings.ju
```

results in

```bash
PipeLine (ContextErr (InfixErr (UnknownSymbol (":" :| []))))
```

I believe @mariari is working on a fix for this by adding a step to contextualise.

**Comment by cwgoes** [comment]
Also, when attempting to (manually) compile an identity term (defined [here](https://github.com/metastatedev/juvix/pull/544/files#diff-082744cc37a9ca8f9c4241587e30920badd5b342d575775f28f22d7082edef65R38)), I seem to run into a parameterisation issue:

```bash
juvix compile test/examples/Id-Strings.ju identity.tz
```

```bash
juvix: src/Juvix/Backends/Michelson/Parameterisation.hs:(38,1)-(39,97): Non-exhaustive patterns in function typeOf
```

**Comment by cwgoes** [comment]
Now:

```bash
juvix parse test/examples/Token.ju
```

results in

```bash
juvix: Prelude.undefined
CallStack (from HasCallStack):
  error, called at src/Debug.hs:66:13 in protolude-0.2.4-Gn8RSsqHn6hJQNfqYGye6Z:Debug
```

**Comment by cwgoes** [comment]
Merging; will follow-up with additional work after #524 is merged.

**Pull request merged**
