### PR TITLE
Multiple File pipeline and Pipeline fixing bugs

### PR DESCRIPTION
**Pull request by mariari**

### CODE REVIEW

**Comment by mariari** [comment]
First pass works as expected for nested (not single!), but the second one nests the currentNameSpace which is bad

**Comment by mariari** [comment]
Bug fixed, was caused by a slight erorr on creation of empty
```haskell
empty :: NameSymbol.T -> T term ty sumRep
empty sym =
  case addPathWithValue sym CurrentNameSpace fullyEmpty of
    Lib.Left _ -> error "impossible"
    Lib.Right x -> x
  where
    fullyEmpty =
      ( T
          { currentNameSpace = NameSpace.empty,
            currentName = sym,
            topLevelMap = HashMap.empty
          }
      )

-- NEW

empty :: NameSymbol.T -> T term ty sumRep
empty sym =
  case addPathWithValue (pure topLevelName <> sym) CurrentNameSpace fullyEmpty of
    Lib.Left _ -> error "impossible"
    Lib.Right x -> x
  where
    fullyEmpty =
      ( T
          { currentNameSpace = NameSpace.empty,
            currentName = sym,
            topLevelMap = HashMap.empty
          }
      )
```

The old would place the single value inside the current name which is incorrect

**Comment by cwgoes** [comment]
Is this ready for review yet?

**Comment by mariari** [comment]
> Is this ready for review yet?

Yes

**Comment by mariari** [comment]
This PR does not include the file downwards, but the Frontend -> Core part, along with bug fixes

**Pull request merged**
